version: '2'

services:

  chronograf:
    image: chronograf:1.8.8-alpine
    container_name: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    environment:
      - TZ=Asia/Taipei

  influxdb:
    image: influxdb:1.8.3
    container_name: influx
    env_file: configuration.env
    ports:
      - "8086:8086"
    volumes:
      - ./config/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./data_influxdb:/var/lib/influx:z
    environment:
      - TZ=Asia/Taipei

  kapacitor:
    image: kapacitor:1.5.7
    container_name: kapacitor
    ports:
      - "9092:9092"
    volumes:
      - ./data_kapacitor:/var/lib/kapacitor:z
      - ./config/kapacitor.conf:/etc/kapacitor/kapacitor.conf  
      
  telegraf:
    image: telegraf:1.16.3
    container_name: telegraf
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
    links:
      - influxdb:influxdb
    environment:
      - TZ=Asia/Taipei

